-- V1__Create_prod_costs_table.sql
------------------------------------------------------------
-- Создание таблицы для хранения статей производственных затрат
------------------------------------------------------------
CREATE TABLE production_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    energy_cost NUMERIC(19, 2),
    labor_hours NUMERIC(19, 2),
    equipment_cost NUMERIC(19, 2),
    material_cost NUMERIC(19, 2),
    logistics_cost NUMERIC(19, 2),
    license_cost NUMERIC(19, 2),
    tax_cost NUMERIC(19, 2),
    social_cost NUMERIC(19, 2),
    amortization_cost NUMERIC(19, 2),
    eco_cost NUMERIC(19, 2),
    equipment_maintenance_cost NUMERIC(19, 2),
    administrative_cost NUMERIC(19, 2),
    rental_cost NUMERIC(19, 2),
    communication_cost NUMERIC(19, 2),
    insurance_cost NUMERIC(19, 2),
    research_and_development_cost NUMERIC(19, 2),
    interest_cost NUMERIC(19, 2),

    CONSTRAINT pk_production_costs PRIMARY KEY (id)
);