-- V2__Create_material_table.sql
------------------------------------------------------------
-- Создание таблицы для хранения сущности Material
------------------------------------------------------------

CREATE TABLE materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    u_code VARCHAR(255) NOT NULL UNIQUE,
    unit VARCHAR(255) NOT NULL,
    cost_per_unit NUMERIC(19, 2) NOT NULL,
    price_per_unit NUMERIC(19, 2) NOT NULL,
    producer VARCHAR(50) NOT NULL,
    quantity NUMERIC(19, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    industry_code VARCHAR(255) NOT NULL,
    plan_period VARCHAR(255),
    production_date DATE NOT NULL,
    strategic BOOLEAN NOT NULL,

    CONSTRAINT pk_materials PRIMARY KEY (id)
);